# Generated by Django 3.1 on 2022-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securehub',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='software',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
