# Generated by Django 3.1 on 2022-02-25 20:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secureApp', '0002_auto_20220225_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='securehub',
            name='level',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='securehub',
            name='licensed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='securehub',
            name='handledBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securehub', to=settings.AUTH_USER_MODEL),
        ),
    ]
